USER_FREE_DAY = "Сегодня не учишься, угомонись"
CREDIT_WEEK = '18 (зачетная) неделя\nУточняйте расписание у преподавателей и в личном кабинете студента НГТУ'
TIMETABLE_NAME = "test.tt_new"
NEWS_BUTTON_TEXT = 'Новости [В разработке]'
MENU_BUTTONS = [['Расписание', NEWS_BUTTON_TEXT],['Настройки бота'],['Сменить группу']]
DISABLED_NOTIFICATION, ENABLED_NOTIFICATION = 'DISABLED_NOTIFICATION', 'ENABLED_NOTIFICATION'   # map(str, range(500,502))
DAY_SCHEDULE, WEEK_SCHEDULE, SPECIFIC_WEEK_SCHEDULE = 'DAY_SCHEDULE', 'WEEK_SCHEDULE', 'SPECIFIC_WEEK_SCHEDULE'     # map(str, range(100,103))
SPECIFY_SEND_MSG_TIME, SPECIFY_SEND_MSG_TIME_OFFSET = 'SPECIFY_SEND_MSG_TIME', 'SPECIFY_SEND_MSG_TIME_OFFSET'
BACK = '-2'
FORCED_BACK = '-3'
START_SETTINGS_HANDLER, SPECIFIC_TIME_SETTINGS_HANDLER, SETTINGS_CONTROLLER_HANDLER, \
OFFSET_TIME_SETTINGS_HANDLER, CLAIM_USER_GROUP_HANDLER, SET_USER_GROUP_HANDLER, \
SCHEDULE_MENU_HANDLER, SPECIFIC_WEEK_SCHEDULE_HANDLER = range(5000, 5008)