CREATE TABLE test.tt_cell
(
    pk integer NOT NULL,
    classname character varying COLLATE pg_catalog."default",
	fk_type_study_work integer,
	remark character varying COLLATE pg_catalog."default",
	day integer,
	starttime character varying COLLATE pg_catalog."default",
	endtime character varying COLLATE pg_catalog."default",
	fk_pair integer,
	is_odd integer,
	fk_study_group integer,
	teacher1 character varying COLLATE pg_catalog."default",
	teacher2 character varying COLLATE pg_catalog."default",
	week1 boolean,
	week2 boolean,
	week3 boolean,
	week4 boolean,
	week5 boolean,
	week6 boolean,
	week7 boolean,
	week8 boolean,
	week9 boolean,
	week10 boolean,
	week11 boolean,
	week12 boolean,
	week13 boolean,
	week14 boolean,
	week15 boolean,
	week16 boolean,
	week17 boolean,
	week18 boolean,
	created_date timestamp without time zone,
	date_add timestamp without time zone NOT NULL DEFAULT now(),
	CONSTRAINT tt_cell_pkey PRIMARY KEY (pk)
)